url: https://eiga.moi
host: eiga.moi
siteName: ACM
poster: 'img.movie-poster'
imdb: '.badge-user a[href*="imdb.com/title"]:nth-child(1)'
insertDomSelector: '#vue'
doubanContainerDom: '<div class="douban-dom" style="width: 1100px;"></div>'